### ISSUE TITLE
亦宣您好,您看看以下是否可更改資料,資料庫名稱要改一下

### ISSUE THREAD

**Issue by isabel112233** [xuanlll17/creditcard#1]
import csv
import sqlite3

db_connection = sqlite3.connect('job.db')
cursor = db_connection.cursor()

area = {'63000000': '臺北市', '64000000':'高雄市', '65000000': '新北市', '66000000': '臺中市', '67000000': '臺南市',
     '68000000': '桃園市','10002000': '宜蘭縣', '10004000': '新竹縣', '10005000': '苗栗縣' ,'10007000': '彰化縣' ,
     '10008000': '南投縣' ,'10009000': '雲林縣','10010000': '嘉義縣' ,'10020000': '嘉義市', '10013000': '屏東縣',
       '10014000': '臺東縣', '10015000': '花蓮縣', '10016000': '澎湖縣','10017000': '基隆市' ,'10018000': '新竹市' ,
       '09020000': '金門縣' ,'09007000': '連江縣'}

with open('job.csv', 'r',encoding='UTF-8') as csv_file:
    csv_reader = csv.DictReader(csv_file)    
    for row in csv_reader:     
        
        row['地區'] = row['地區'].replace(row['地區'],area[row['地區']])
        
        sql = '''
            INSERT INTO job (年月,地區,產業別,職業類別,信用卡交易筆數,'信用卡交易金額[新台幣]')VALUES (?,?,?,?,?,?)
            '''
        cursor.execute(sql)

db_connection.commit()
db_connection.close()

**Comment by xuanlll17** [comment]
收到，謝謝！

經測試後發現：

- ```row['地區'] = row['地區'].replace(row['地區'],area[row['地區']])```，若遇到資料本身並非使用代號會產生錯誤，其餘代號有對應的值可以轉換成功！

- 程式碼改成 -> ```row['地區'] = area.get(row['地區'], row['地區'])```，若找不到對應的值則保持原本，可以解決上述程式碼問題！

- 目前僅轉換完職業及年齡的部分，若先前資料庫已輸入資料，要看轉換完的資料是否輸入成功，拉至最後可看見

- 以下是完整程式碼：
```
import csv
import sqlite3

db_connection = sqlite3.connect("creditcard.db")
cursor = db_connection.cursor()

area = {
    "63000000": "臺北市",
    "64000000": "高雄市",
    "65000000": "新北市",
    "66000000": "臺中市",
    "67000000": "臺南市",
    "68000000": "桃園市",
    "10002000": "宜蘭縣",
    "10004000": "新竹縣",
    "10005000": "苗栗縣",
    "10007000": "彰化縣",
    "10008000": "南投縣",
    "10009000": "雲林縣",
    "10010000": "嘉義縣",
    "10020000": "嘉義市",
    "10013000": "屏東縣",
    "10014000": "臺東縣",
    "10015000": "花蓮縣",
    "10016000": "澎湖縣",
    "10017000": "基隆市",
    "10018000": "新竹市",
    "09020000": "金門縣",
    "09007000": "連江縣",
}

with open("job.csv", "r", encoding="UTF-8") as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        #row['地區'] = row['地區'].replace(row['地區'],area[row['地區']])
        # 遇到非代號會有問題，其餘有對應代號轉換成功
        # 使用get方法，如果找不到對應的鍵，就保持原來的值
        row['地區'] = area.get(row['地區'], row['地區'])

        #print(row)

        sql = """
            INSERT INTO job (年,月,地區,產業別,職業類別,信用卡交易筆數,'信用卡交易金額[新台幣]')VALUES (?,?,?,?,?,?,?)
            """
        values = (
        row["年"],
        row["月"],
        row["地區"],
        row["產業別"],
        row["職業類別"],
        row["信用卡交易筆數"],
        row["信用卡交易金額[新台幣]"]
        )

        
        cursor.execute(sql, values)


db_connection.commit()
db_connection.close()
```
